title: mlops
email: your-email@example.com
description: >- 
  Open-source tool for tracking & monitoring machine learning models.
url: "https://mlops-ai.github.io/mlops/" 
twitter_username: jekyllrb
github_username:  "https://mlops-ai.github.io/mlops/"

theme: just-the-docs

